// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDReNsf8Bvvd_-jlEY8leWJkLsfXumG3uk',
    appId: '1:423968387240:web:87bdf94f995de824da129d',
    messagingSenderId: '423968387240',
    projectId: 'detrumpez-vous-site',
    authDomain: 'detrumpez-vous-site.firebaseapp.com',
    storageBucket: 'detrumpez-vous-site.firebasestorage.app',
    measurementId: 'G-D0Z1HGD9HC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsl5XWoKryPHRR9OCq6mZmcYP8KljhzaI',
    appId: '1:423968387240:android:08c3ad0a83f3f9ddda129d',
    messagingSenderId: '423968387240',
    projectId: 'detrumpez-vous-site',
    storageBucket: 'detrumpez-vous-site.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJzSsEBTAY-Zi7G_5ddJ0LDn6Lvv7mNFU',
    appId: '1:423968387240:ios:277d761e6a45f4bdda129d',
    messagingSenderId: '423968387240',
    projectId: 'detrumpez-vous-site',
    storageBucket: 'detrumpez-vous-site.firebasestorage.app',
    iosBundleId: 'com.detrumpezvous.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJzSsEBTAY-Zi7G_5ddJ0LDn6Lvv7mNFU',
    appId: '1:423968387240:ios:277d761e6a45f4bdda129d',
    messagingSenderId: '423968387240',
    projectId: 'detrumpez-vous-site',
    storageBucket: 'detrumpez-vous-site.firebasestorage.app',
    iosBundleId: 'com.detrumpezvous.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDReNsf8Bvvd_-jlEY8leWJkLsfXumG3uk',
    appId: '1:423968387240:web:af8c5d9190ee354fda129d',
    messagingSenderId: '423968387240',
    projectId: 'detrumpez-vous-site',
    authDomain: 'detrumpez-vous-site.firebaseapp.com',
    storageBucket: 'detrumpez-vous-site.firebasestorage.app',
    measurementId: 'G-WWC2RRP85X',
  );
}
